name: CI

on: [push]

jobs:
  scope:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy files needed for tests
      run: |
        swift build --build-tests -Xswiftc -suppress-warnings
        cp -R Tests/CarthageKitTests/Resources ./.build/debug/CarthagePackageTests.xctest/Contents
        cp Tests/CarthageKitTests/fixtures/CartfilePrivateOnly.zip ./.build/debug/CarthagePackageTests.xctest/Contents/Resources
        script/copy-fixtures ./.build/debug/CarthagePackageTests.xctest/Contents/Resources
    - name: Testing for macOS
      uses: undefinedlabs/scope-for-swift-action@v1
      with: 
        dsn: ${{ secrets.SCOPE_DSN }}
        platform: macos
        codePath: true
